<?php
require_once('../db.php');
require_once('../fpdf/fpdf.php');

try {
    $sql = "SELECT * FROM items ORDER BY item_id ASC";
    $stmt = $conn->prepare($sql);
    $stmt->execute();
    $items = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $pdf = new FPDF();
    $pdf->AddPage();
    
    $pdf->SetFont('Arial', 'B', 18);
    $pdf->Cell(0, 10, 'SLC BOOKSTORE', 0, 1, 'C');
    $pdf->SetFont('Arial', '', 12);
    $pdf->Cell(0, 8, 'Inventory Report', 0, 1, 'C');
    $pdf->Cell(0, 8, 'Generated: ' . date('F d, Y h:i A'), 0, 1, 'C');
    $pdf->Ln(5);

    $pdf->SetFont('Arial', 'B', 10);
    $pdf->SetFillColor(30, 77, 123);
    $pdf->SetTextColor(255, 255, 255);
    
    $pdf->Cell(15, 8, 'ID', 1, 0, 'C', true);
    $pdf->Cell(30, 8, 'SKU', 1, 0, 'C', true);
    $pdf->Cell(60, 8, 'Item Name', 1, 0, 'C', true);
    $pdf->Cell(25, 8, 'Price', 1, 0, 'C', true);
    $pdf->Cell(20, 8, 'Stock', 1, 0, 'C', true);
    $pdf->Cell(40, 8, 'Date Added', 1, 1, 'C', true);

    $pdf->SetFont('Arial', '', 9);
    $pdf->SetTextColor(0, 0, 0);
    
    $total = 0;
    $totalStock = 0;
    
    foreach ($items as $item) {
        $pdf->Cell(15, 7, $item['item_id'], 1, 0, 'C');
        $pdf->Cell(30, 7, $item['sku'], 1, 0, 'L');
        $pdf->Cell(60, 7, substr($item['item_name'], 0, 30), 1, 0, 'L');
        $pdf->Cell(25, 7, 'P ' . number_format($item['item_price'], 2), 1, 0, 'R');
        $pdf->Cell(20, 7, $item['stock'], 1, 0, 'C');
        $pdf->Cell(40, 7, date('M d, Y', strtotime($item['created_at'])), 1, 1, 'C');
        
        $total += $item['item_price'] * $item['stock'];
        $totalStock += $item['stock'];
    }

    $pdf->Ln(3);
    $pdf->SetFont('Arial', 'B', 10);
    $pdf->Cell(105, 8, 'Total Items: ' . count($items), 0, 0, 'L');
    $pdf->Cell(45, 8, 'Total Stock: ' . $totalStock, 0, 0, 'R');
    $pdf->Cell(40, 8, 'Value: P ' . number_format($total, 2), 0, 1, 'R');

    $pdf->Ln(10);
    $pdf->SetFont('Arial', 'I', 8);
    $pdf->Cell(0, 5, 'Report generated by SLC Bookstore System', 0, 1, 'C');

    $pdf->Output('I', 'inventory_report_' . date('Y-m-d') . '.pdf');

} catch (PDOException $e) {
    die("Error generating report: " . $e->getMessage());
}
?>